### ISSUE TITLE
Convert page to flexbox

### ISSUE THREAD

**Issue by robertdenton** [rgpages/election-2016-general#6]
Only 14 spots to change, will allow for topballotitems to move to the top on mobile.

**Comment by robertdenton** [comment]
PURE USES FLEXBOX OMG HOW DID I NOT KNOW THIS. 

_layout.scss > line 67

``` css
#tbi{ order: -1; }
@media all and (min-width: 960px) {
    #tbi { order: 9999; }
}
```
